swagger: '2.0'
info:
  title: Pharmacy Adherence Solution API
  description: 'API to try to solve the problem of Non Adherence'
  version: 1.0.0
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /lfauth:
    get:
      summary: This is responsible for authenticating the user
      description: |
        This takes in a patient or doctor object
      tags:
        - AUTH
      operationId: verifyUser
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFAuthRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFAuthResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /lfcreateaccount:
    post:
      summary: This allows the frontend to create a new account for the user
      description: |
        This takes in a patient or doctor object
      tags:
        - AUTH
      operationId: createUser
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFCreateUserRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFCreateUserResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /lfenablereminder:
    post:
      summary: This is responsible for enabling a reminder for a medicine
      description: |
        This takes in a medicine object
      tags:
        - REMINDER
      operationId: enableReminder
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFEnableReminderRequest'
      responses:
        '200':
          description: successfully changed reminder status
        '403':
          description: Unauthorized9
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /lfgetactivemedicines:
    get:
      summary: This allows front end to grab all active medicines
      tags:
        - MEDICINE
      operationId: activeMedicine
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFGetActiveMedicinesRequest'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/LFGetActiveMedicinesResponse'
        '403':
          description:
            successfully grabbed active medicines for active user
          schema:
            $ref: '#/definitions/Error'
  
  /lfcreatemedicine:
    post:
      summary:  This allows doctors to create an entry in the medicines table for a patient
      tags:
        - MEDICINE
      operationId: createMedicine
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFCreateMedicineRequest'
      responses:
        '200':
          description: successully created the entry in the medicines table
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
            
  /lfupdatemedicine:
    post:
      summary:  This allows doctors to update an entry in the medicine table
      tags:
        - MEDICINE
      operationId: updateMedicine
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFUpdateMedicineRequest'
      responses:
        '200':
          description: successully updated the entry in the medicines table
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
      
  /lfchat:
    post:
      summary: This is responsible for iniating a conversation with lex
      description: |
        This takes in a doctor or patient object as well as a requestType
      tags:
        - CHAT
      operationId: chat
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFChatRequest'
      responses:
        '200':
          description: OK
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    
  /lfgrabmessages:
    get:
      summary: This is responsible for retrieving the messages of a doctor or patient
      description: |
        This takes in a doctor or patient object as well as the requestType
      tags:
        - CHAT
      operationId: grabmessages
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFGrabMessagesRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFGrabMessagesResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  

  /lfcheckformulary:
    get:
      summary: This is responsible for checking if a medicine is covered under an insurance
      description: |
        This takes in a medicine object
      tags:
        - INSURANCE
      operationId: checkFormulary
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFCheckFormularyRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFCheckFormularyResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /lfgoodrx:
    get:
      summary: This is responsible for retrieving goodrx coupons
      description: |
        This takes in a medicine object
      tags:
        - INSURANCE
      operationId: goodRX
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFGoodRXRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFGoodRXResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /lfsinglecare:
    get:
      summary: This is responsible for retrieving singlecare coupons
      description: |
        This takes in a medicine object
      tags:
        - INSURANCE
      operationId: singlecare
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFSinglecareRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFSinglecareResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /lfwellrx:
    get:
      summary: This is responsible for retrieving wellrx coupons
      description: |
        This takes in a medicine object
      tags:
        - INSURANCE
      operationId: wellRX
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFWellRXRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFWellRXResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  
definitions:
  LFAuthRequest:
    type: object
    properties:
      patient:
        type: object
        $ref: '#/definitions/Patient'
      doctor:
        type: object
        $ref: '#/definitions/Doctor'
      role:
        type: string
      action:
        type: string
  LFAuthResponse:
    type: object
    properties:
      authMessage:
        type: string
        
  LFCreateUserRequest:
    type: object
    properties:
      patient:
        type: object
        $ref: '#/definitions/Patient'
      doctor:
        type: object
        $ref: '#/definitions/Doctor'
  
  LFCreateUserResponse:
    type: object
    properties:
      patient:
        type: object
        $ref: '#/definitions/Patient'
      doctor:
        type: object
        $ref: '#/definitions/Doctor'
  
  LFCreateMedicineRequest:
    type: object
    properties:
      pharmacy:
        type: object
        $ref: '#/definitions/Pharmacy'
      medicine:
        type: object
        $ref: '#/definitions/Medicine'
  
  LFUpdateMedicineRequest:
    type: object
    properties:
      medicine:
        type: object
        $ref: '#/definitions/Medicine'
  
      
      
  LFEnableReminderRequest:
    type: object
    properties:
      medicine:
        type: object
        $ref: '#/definitions/Medicine'

  LFChatRequest:
    type: object
    properties:
      doctor:
        type: object
        $ref: '#/definitions/Doctor'
      requestType:
        type: string
      request:
        type: object
        properties:
          patient:
            $ref: '#/definitions/Patient'
    

  LFGrabMessagesRequest:
    type: object
    properties:
      doctor:
        type: object
        $ref: '#/definitions/Doctor'
      requestType:
        type: string
      patient:
        type: object
        $ref: '#/definitions/Patient'

  LFGrabMessagesResponse:
    type: array
    items:
      $ref: '#/definitions/Messages'
        
  LFGetActiveMedicinesRequest:
    type: object
    properties:
      patient:
        type: object
        $ref: '#/definitions/Patient'
      
  
  LFGetActiveMedicinesResponse:
    type: object
    properties:
      medicines:
        type: array
        items:
          $ref: '#/definitions/Medicine'
      

  LFCheckFormularyRequest:
    type: object
    properties:
      medicine:
        $ref: '#/definitions/Medicine'
  
  LFCheckFormularyResponse:
    type: object
    properties:
      covered:
        type: string
    
  
  LFGoodRXRequest:
    type: object
    $ref: '#/definitions/InsuranceRequest'
  
  LFGoodRXResponse:
    type: object
    $ref: '#/definitions/InsuranceResponse'
    
    
  
  LFSinglecareRequest:
    type: object
    $ref: '#/definitions/InsuranceRequest'
  
  LFSinglecareResponse:
    type: object
    $ref: '#/definitions/InsuranceResponse'
  
  LFWellRXRequest:
    type: object
    $ref: '#/definitions/InsuranceRequest'
  
  LFWellRXResponse:
    type: object
    $ref: '#/definitions/InsuranceResponse'
    
  InsuranceRequest:
    type: object
    properties:
      medicine:
        type: object
        $ref: '#/definitions/Medicine'
        
  InsuranceResponse:
    type: object
    properties:
      pharmacies:
        type: array
        items:
          $ref: '#/definitions/Pharmacy'
      coupons:
        type: array
        items:
          $ref: '#/definitions/Coupon'
  
  Coupon:
    type: object
    properties:
      bin:
        type: string
      pcn:
        type: string
      group:
        type: string
      id:
        type: string
      price:
        type: string
    
  Pharmacy:
    type: object
    properties:
      name:
        type: string
      location:
        type: string
  
  Patient:
    type: object
    properties:
      firstName: 
          type: string
      lastName: 
        type: string
      address:
        type: string
      dob:
        type: string
      insurance:
        type: string
      preferredLocation:
        type: string
      email:
        type: string
      doctorFirstName: 
          type: string
      doctorLastName: 
        type: string
      doctorOfficeAddress:
        type: string
      
          
  Doctor:
    type: object
    properties:
      firstName: 
          type: string
      lastName: 
        type: string
      officeAddress:
        type: string
      npi:
        type: string
  
        
      
      
  Medicine:
    type: object
    properties:
      doctor:
        type: object
        $ref: '#/definitions/Doctor'
      patient:
        type: object
        $ref: '#/definitions/Patient'
      name:
          type: string
      dosage:
        type: string
      quantity:
        type: string
      refills:
        type: string
      schedule:
        type: object
        $ref: '#/definitions/Schedule'
        
    
  Schedule:
    type: object
    properties:
      recentReminderDateTime:
        type: string
      currentFrequency:
        type: string
      overallFrequency:
        type: string
      frequencyType:
        type: string
      enddate:
        type: string
      additionalInstructions:
        type: string
      
    
  Messages:
    type: object
    properties:
      message:
        type: object
        $ref: '#/definitions/Message'
  
  Message:
    type: object
    properties:
      doctor:
        type: object
        $ref: '#/definitions/Doctor'
      patient:
        type: object
        $ref: '#/definitions/Patient'
      messageBody:
        type: string
      request:
        type: object
        $ref: '#/definitions/Request'
  
  Request:
    type: object
    properties:
      requestType:
        type: string
      dateTime:
        type: string
      responded:
        type: string
        
        
  
        

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
