swagger: '2.0'
info:
  title: Pharmacy Adherence Solution API
  description: 'API to try to solve the problem of Non Adherence'
  version: 1.0.0
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /lfauth:
    get:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in an email, password, role, and action
      tags:
        - AUTH
      operationId: verifyUser
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFAuthRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFAuthResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /lfenablereminder:
    post:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in an email, password, role, and action
      tags:
        - REMINDER
      operationId: enableReminder
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFEnableReminderRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFEnableReminderResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /lfgeneratereminderemail:
    get:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in an email, password, role, and action
      tags:
        - REMINDER
      operationId: generatereminderemail
      produces:
        - application/json
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFGenerateReminderEmailRequest'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /lftreatmentplanupdate:
    post:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in an email, password, role, and action
      tags:
        - TREATMENT
      operationId: treatmentPlanUpdate
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFTreatmentPlanUpdateRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFTreatmentPlanUpdateResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /lftreatmentplancreate:
    post:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in an email, password, role, and action
      tags:
        - TREATMENT
      operationId: treatmentPlanCreate
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFTreatmentPlanCreateRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFTreatmentPlanCreateResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /lfchat:
    post:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in an email, password, role, and action
      tags:
        - CHAT
      operationId: chat
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFChatRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFChatResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    
  /lfgrabmessages:
    get:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in an email, password, role, and action
      tags:
        - CHAT
      operationId: grabmessages
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFGrabMessagesRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFGrabMessagesResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  

  /lfcheckformulary:
    get:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in an email, password, role, and action
      tags:
        - INSURANCE
      operationId: checkFormulary
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFCheckFormularyRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFCheckFormularyResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /lfgoodrx:
    get:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in an email, password, role, and action
      tags:
        - INSURANCE
      operationId: goodRX
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFGoodRXRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFGoodRXResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /lfsinglecare:
    get:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in an email, password, role, and action
      tags:
        - INSURANCE
      operationId: singlecare
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFSinglecareRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFSinglecareResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  /lfwellrx:
    get:
      summary: The endpoint for the Natural Language Understanding API.
      description: |
        This API takes in an email, password, role, and action
      tags:
        - INSURANCE
      operationId: wellRX
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/LFWellRXRequest'
      responses:
        '200':
          description: A Chatbot response
          schema:
            $ref: '#/definitions/LFWellRXResponse'
        '403':
          description: Unauthorized
          schema:
            $ref: '#/definitions/Error'
        '500':
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  
  
definitions:
  LFAuthRequest:
    type: object
    properties:
      email:
        type: string
      password::
        type: string
      role:
        type: string
      action:
        type: string
        
  LFAuthResponse:
    type: object
    properties:
      user:
        type: string
  
  LFEnableReminderRequest:
    type: object
    properties:
      Patient:
        type: object


  LFEnableReminderResponse:
    type: object
  
  LFChatRequest:
    type: object
    properties:
      doctor:
        type: object
      requestType:
        type: string
      request:
        type: object
        properties:
          patient:
            $ref: '#/definitions/Patient'

  LFChatResponse:
    type: object
    

  LFGrabMessagesRequest:
    type: object
    properties:
      doctor:
        type: object
      requestType:
        type: string
      patient:
        type: object

  LFGrabMessagesResponse:
    type: object
    properties:
      messages:
        type: object
  
  
  LFGenerateReminderEmailRequest:
    type: object
  
    
  LFTreatmentPlanUpdateRequest:
    type: object
  
  LFTreatmentPlanUpdateResponse:
    type: object
    
  LFTreatmentPlanCreateRequest:
    type: object
  
  
  LFTreatmentPlanCreateResponse:
    type: object
      

  LFCheckFormularyRequest:
    type: object
  
  LFCheckFormularyResponse:
    type: object
    
  
  LFGoodRXRequest:
    type: object
  
  LFGoodRXResponse:
    type: object
  
  LFSinglecareRequest:
    type: object
  
  LFSinglecareResponse:
    type: object
  
  LFWellRXRequest:
    type: object
  
  LFWellRXResponse:
    type: object
  
  Patient:
    type: object
    properties:
      firstName: 
          type: string
      lastName: 
        type: string
      address:
        type: string
      dob:
        type: string
      insurance:
        type: string
      preferredLocation:
        type: string
      email:
        type: string
      doctorFirstName: 
          type: string
      doctorLastName: 
        type: string
      doctorOfficeAddress:
        type: string
      
          
  Doctor:
    type: object
    properties:
      firstName: 
          type: string
      lastName: 
        type: string
      officeAddress:
        type: string
      npi:
        type: string
  
        
      
      
  Medicine:
    type: object
    properties:
      name:
          type: string
      dosage:
        type: string
      quantity:
        type: string
      refills:
        type: string
      schedule:
        type: object
        
    
  Schedule:
    type: object
    properties:
      recentReminderDateTime:
        type: string
      currentFrequency:
        type: string
      overallFrequency:
        type: string
      frequencyType:
        type: string
      enddate:
        type: string
      additionalInstructions:
        type: string
      
    
  Messages:
    type: object
    properties:
      message:
        type: object
  
  Message:
    type: object
    properties:
      doctor:
        type: object
      patient:
        type: object
      messageBody:
        type: string
      request:
        type: object
  
  Request:
    type: object
    properties:
      requestType:
        type: string
      dateTime:
        type: string
      responded:
        type: string
        
        
  
        

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string